version: '3'

services:
  database:
    image: postgres:13-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database/.env
    volumes:
      - ./database/init_data/:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis_cashe
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


volumes:
  cache:
    driver: local