"""partition_on_user_agent_platform

Revision ID: 93f91144856e
Revises: 17aab65a0bd8
Create Date: 2022-08-01 23:46:35.087835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f91144856e'
down_revision = '17aab65a0bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'role_permission', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.add_column('user_history', sa.Column('platform', sa.String(), server_default='other', nullable=False))
    op.create_unique_constraint(None, 'user_history', ['id'])
    op.create_unique_constraint(None, 'user_history', ['id', 'platform'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_history', type_='unique')
    op.drop_constraint(None, 'user_history', type_='unique')
    op.drop_column('user_history', 'platform')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'role_permission', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
